// Generated by gencpp from file cartographer_ros_msgs/GetSubmapRequest.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_GETSUBMAPREQUEST_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_GETSUBMAPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cartographer_ros_msgs
{
template <class ContainerAllocator>
struct GetSubmapRequest_
{
  typedef GetSubmapRequest_<ContainerAllocator> Type;

  GetSubmapRequest_()
    : submap_index(0)
    , write_map(false)  {
    }
  GetSubmapRequest_(const ContainerAllocator& _alloc)
    : submap_index(0)
    , write_map(false)  {
  (void)_alloc;
    }



   typedef int32_t _submap_index_type;
  _submap_index_type submap_index;

   typedef uint8_t _write_map_type;
  _write_map_type write_map;




  typedef boost::shared_ptr< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetSubmapRequest_

typedef ::cartographer_ros_msgs::GetSubmapRequest_<std::allocator<void> > GetSubmapRequest;

typedef boost::shared_ptr< ::cartographer_ros_msgs::GetSubmapRequest > GetSubmapRequestPtr;
typedef boost::shared_ptr< ::cartographer_ros_msgs::GetSubmapRequest const> GetSubmapRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cartographer_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'cartographer_ros_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_slam/cartographer_superbuild/cartographer_ros/cartographer_ros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74e8f1e9dcff0b323f29cf3759b56d04";
  }

  static const char* value(const ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74e8f1e9dcff0b32ULL;
  static const uint64_t static_value2 = 0x3f29cf3759b56d04ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartographer_ros_msgs/GetSubmapRequest";
  }

  static const char* value(const ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 submap_index\n\
bool write_map\n\
";
  }

  static const char* value(const ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.submap_index);
      stream.next(m.write_map);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetSubmapRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartographer_ros_msgs::GetSubmapRequest_<ContainerAllocator>& v)
  {
    s << indent << "submap_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.submap_index);
    s << indent << "write_map: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.write_map);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_GETSUBMAPREQUEST_H
