// Generated by gencpp from file cartographer_ros_msgs/GetSubmap.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_GETSUBMAP_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_GETSUBMAP_H

#include <ros/service_traits.h>


#include <cartographer_ros_msgs/GetSubmapRequest.h>
#include <cartographer_ros_msgs/GetSubmapResponse.h>


namespace cartographer_ros_msgs
{

struct GetSubmap
{

typedef GetSubmapRequest Request;
typedef GetSubmapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetSubmap
} // namespace cartographer_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cartographer_ros_msgs::GetSubmap > {
  static const char* value()
  {
    return "d186db8adc3c0aec02e182098a6cf86e";
  }

  static const char* value(const ::cartographer_ros_msgs::GetSubmap&) { return value(); }
};

template<>
struct DataType< ::cartographer_ros_msgs::GetSubmap > {
  static const char* value()
  {
    return "cartographer_ros_msgs/GetSubmap";
  }

  static const char* value(const ::cartographer_ros_msgs::GetSubmap&) { return value(); }
};


// service_traits::MD5Sum< ::cartographer_ros_msgs::GetSubmapRequest> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::GetSubmap > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::GetSubmapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::GetSubmap >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::GetSubmapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::GetSubmapRequest> should match 
// service_traits::DataType< ::cartographer_ros_msgs::GetSubmap > 
template<>
struct DataType< ::cartographer_ros_msgs::GetSubmapRequest>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::GetSubmap >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::GetSubmapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cartographer_ros_msgs::GetSubmapResponse> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::GetSubmap > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::GetSubmapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::GetSubmap >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::GetSubmapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::GetSubmapResponse> should match 
// service_traits::DataType< ::cartographer_ros_msgs::GetSubmap > 
template<>
struct DataType< ::cartographer_ros_msgs::GetSubmapResponse>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::GetSubmap >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::GetSubmapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_GETSUBMAP_H
