// Generated by gencpp from file cartographer_ros_msgs/ManualLoop.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_MANUALLOOP_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_MANUALLOOP_H

#include <ros/service_traits.h>


#include <cartographer_ros_msgs/ManualLoopRequest.h>
#include <cartographer_ros_msgs/ManualLoopResponse.h>


namespace cartographer_ros_msgs
{

struct ManualLoop
{

typedef ManualLoopRequest Request;
typedef ManualLoopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManualLoop
} // namespace cartographer_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cartographer_ros_msgs::ManualLoop > {
  static const char* value()
  {
    return "1c480aaf8297c71d4cb9e335eba91f51";
  }

  static const char* value(const ::cartographer_ros_msgs::ManualLoop&) { return value(); }
};

template<>
struct DataType< ::cartographer_ros_msgs::ManualLoop > {
  static const char* value()
  {
    return "cartographer_ros_msgs/ManualLoop";
  }

  static const char* value(const ::cartographer_ros_msgs::ManualLoop&) { return value(); }
};


// service_traits::MD5Sum< ::cartographer_ros_msgs::ManualLoopRequest> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::ManualLoop > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::ManualLoopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::ManualLoop >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::ManualLoopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::ManualLoopRequest> should match 
// service_traits::DataType< ::cartographer_ros_msgs::ManualLoop > 
template<>
struct DataType< ::cartographer_ros_msgs::ManualLoopRequest>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::ManualLoop >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::ManualLoopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cartographer_ros_msgs::ManualLoopResponse> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::ManualLoop > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::ManualLoopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::ManualLoop >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::ManualLoopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::ManualLoopResponse> should match 
// service_traits::DataType< ::cartographer_ros_msgs::ManualLoop > 
template<>
struct DataType< ::cartographer_ros_msgs::ManualLoopResponse>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::ManualLoop >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::ManualLoopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_MANUALLOOP_H
