// Generated by gencpp from file cartographer_ros_msgs/ManualLoopResponse.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_MANUALLOOPRESPONSE_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_MANUALLOOPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cartographer_ros_msgs
{
template <class ContainerAllocator>
struct ManualLoopResponse_
{
  typedef ManualLoopResponse_<ContainerAllocator> Type;

  ManualLoopResponse_()
    : msg()
    , code(0)  {
    }
  ManualLoopResponse_(const ContainerAllocator& _alloc)
    : msg(_alloc)
    , code(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;

   typedef int8_t _code_type;
  _code_type code;




  typedef boost::shared_ptr< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ManualLoopResponse_

typedef ::cartographer_ros_msgs::ManualLoopResponse_<std::allocator<void> > ManualLoopResponse;

typedef boost::shared_ptr< ::cartographer_ros_msgs::ManualLoopResponse > ManualLoopResponsePtr;
typedef boost::shared_ptr< ::cartographer_ros_msgs::ManualLoopResponse const> ManualLoopResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cartographer_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'cartographer_ros_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_slam/cartographer_superbuild/cartographer_ros/cartographer_ros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21d8bea45396b7dc24034db0fb3f9f05";
  }

  static const char* value(const ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21d8bea45396b7dcULL;
  static const uint64_t static_value2 = 0x24034db0fb3f9f05ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartographer_ros_msgs/ManualLoopResponse";
  }

  static const char* value(const ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msg\n\
int8 code\n\
\n\
";
  }

  static const char* value(const ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManualLoopResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartographer_ros_msgs::ManualLoopResponse_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
    s << indent << "code: ";
    Printer<int8_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_MANUALLOOPRESPONSE_H
