// Generated by gencpp from file cartographer_ros_msgs/ManualLoopRequest.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_MANUALLOOPREQUEST_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_MANUALLOOPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cartographer_ros_msgs
{
template <class ContainerAllocator>
struct ManualLoopRequest_
{
  typedef ManualLoopRequest_<ContainerAllocator> Type;

  ManualLoopRequest_()
    : option()
    , trajectoryid(0)
    , signal(false)  {
    }
  ManualLoopRequest_(const ContainerAllocator& _alloc)
    : option(_alloc)
    , trajectoryid(0)
    , signal(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _option_type;
  _option_type option;

   typedef int8_t _trajectoryid_type;
  _trajectoryid_type trajectoryid;

   typedef uint8_t _signal_type;
  _signal_type signal;




  typedef boost::shared_ptr< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ManualLoopRequest_

typedef ::cartographer_ros_msgs::ManualLoopRequest_<std::allocator<void> > ManualLoopRequest;

typedef boost::shared_ptr< ::cartographer_ros_msgs::ManualLoopRequest > ManualLoopRequestPtr;
typedef boost::shared_ptr< ::cartographer_ros_msgs::ManualLoopRequest const> ManualLoopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cartographer_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'cartographer_ros_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_slam/cartographer_superbuild/cartographer_ros/cartographer_ros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fad3ae82557f64cf475bea2e23b61eb1";
  }

  static const char* value(const ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfad3ae82557f64cfULL;
  static const uint64_t static_value2 = 0x475bea2e23b61eb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartographer_ros_msgs/ManualLoopRequest";
  }

  static const char* value(const ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string option\n\
int8 trajectoryid\n\
bool signal\n\
";
  }

  static const char* value(const ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.option);
      stream.next(m.trajectoryid);
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManualLoopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartographer_ros_msgs::ManualLoopRequest_<ContainerAllocator>& v)
  {
    s << indent << "option: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.option);
    s << indent << "trajectoryid: ";
    Printer<int8_t>::stream(s, indent + "  ", v.trajectoryid);
    s << indent << "signal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_MANUALLOOPREQUEST_H
