// Generated by gencpp from file cartographer_ros_msgs/OperatepbstreamRequest.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_OPERATEPBSTREAMREQUEST_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_OPERATEPBSTREAMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cartographer_ros_msgs
{
template <class ContainerAllocator>
struct OperatepbstreamRequest_
{
  typedef OperatepbstreamRequest_<ContainerAllocator> Type;

  OperatepbstreamRequest_()
    : option()
    , floor(0)
    , md5()
    , data()  {
    }
  OperatepbstreamRequest_(const ContainerAllocator& _alloc)
    : option(_alloc)
    , floor(0)
    , md5(_alloc)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _option_type;
  _option_type option;

   typedef int8_t _floor_type;
  _floor_type floor;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _md5_type;
  _md5_type md5;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OperatepbstreamRequest_

typedef ::cartographer_ros_msgs::OperatepbstreamRequest_<std::allocator<void> > OperatepbstreamRequest;

typedef boost::shared_ptr< ::cartographer_ros_msgs::OperatepbstreamRequest > OperatepbstreamRequestPtr;
typedef boost::shared_ptr< ::cartographer_ros_msgs::OperatepbstreamRequest const> OperatepbstreamRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cartographer_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'cartographer_ros_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_slam/cartographer_superbuild/cartographer_ros/cartographer_ros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "77dacebdf349f4927c8c3ae70f016248";
  }

  static const char* value(const ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x77dacebdf349f492ULL;
  static const uint64_t static_value2 = 0x7c8c3ae70f016248ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartographer_ros_msgs/OperatepbstreamRequest";
  }

  static const char* value(const ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string option\n\
int8 floor\n\
string md5\n\
char[] data\n\
";
  }

  static const char* value(const ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.option);
      stream.next(m.floor);
      stream.next(m.md5);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OperatepbstreamRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartographer_ros_msgs::OperatepbstreamRequest_<ContainerAllocator>& v)
  {
    s << indent << "option: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.option);
    s << indent << "floor: ";
    Printer<int8_t>::stream(s, indent + "  ", v.floor);
    s << indent << "md5: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.md5);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_OPERATEPBSTREAMREQUEST_H
