// Generated by gencpp from file cartographer_ros_msgs/OperatepbstreamResponse.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_OPERATEPBSTREAMRESPONSE_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_OPERATEPBSTREAMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cartographer_ros_msgs
{
template <class ContainerAllocator>
struct OperatepbstreamResponse_
{
  typedef OperatepbstreamResponse_<ContainerAllocator> Type;

  OperatepbstreamResponse_()
    : msg()
    , result(0)
    , data()  {
    }
  OperatepbstreamResponse_(const ContainerAllocator& _alloc)
    : msg(_alloc)
    , result(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;

   typedef uint32_t _result_type;
  _result_type result;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> const> ConstPtr;

}; // struct OperatepbstreamResponse_

typedef ::cartographer_ros_msgs::OperatepbstreamResponse_<std::allocator<void> > OperatepbstreamResponse;

typedef boost::shared_ptr< ::cartographer_ros_msgs::OperatepbstreamResponse > OperatepbstreamResponsePtr;
typedef boost::shared_ptr< ::cartographer_ros_msgs::OperatepbstreamResponse const> OperatepbstreamResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cartographer_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'cartographer_ros_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_slam/cartographer_superbuild/cartographer_ros/cartographer_ros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c492248e2e31bf4b061da7e206df7885";
  }

  static const char* value(const ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc492248e2e31bf4bULL;
  static const uint64_t static_value2 = 0x061da7e206df7885ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartographer_ros_msgs/OperatepbstreamResponse";
  }

  static const char* value(const ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msg\n\
uint32 result\n\
char[] data\n\
";
  }

  static const char* value(const ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
      stream.next(m.result);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OperatepbstreamResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartographer_ros_msgs::OperatepbstreamResponse_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
    s << indent << "result: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.result);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_OPERATEPBSTREAMRESPONSE_H
