// Generated by gencpp from file cartographer_ros_msgs/Operatepbstream.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_OPERATEPBSTREAM_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_OPERATEPBSTREAM_H

#include <ros/service_traits.h>


#include <cartographer_ros_msgs/OperatepbstreamRequest.h>
#include <cartographer_ros_msgs/OperatepbstreamResponse.h>


namespace cartographer_ros_msgs
{

struct Operatepbstream
{

typedef OperatepbstreamRequest Request;
typedef OperatepbstreamResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Operatepbstream
} // namespace cartographer_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cartographer_ros_msgs::Operatepbstream > {
  static const char* value()
  {
    return "95103b6286636b56ab523be0c9f38932";
  }

  static const char* value(const ::cartographer_ros_msgs::Operatepbstream&) { return value(); }
};

template<>
struct DataType< ::cartographer_ros_msgs::Operatepbstream > {
  static const char* value()
  {
    return "cartographer_ros_msgs/Operatepbstream";
  }

  static const char* value(const ::cartographer_ros_msgs::Operatepbstream&) { return value(); }
};


// service_traits::MD5Sum< ::cartographer_ros_msgs::OperatepbstreamRequest> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::Operatepbstream > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::OperatepbstreamRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::Operatepbstream >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::OperatepbstreamRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::OperatepbstreamRequest> should match 
// service_traits::DataType< ::cartographer_ros_msgs::Operatepbstream > 
template<>
struct DataType< ::cartographer_ros_msgs::OperatepbstreamRequest>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::Operatepbstream >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::OperatepbstreamRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cartographer_ros_msgs::OperatepbstreamResponse> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::Operatepbstream > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::OperatepbstreamResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::Operatepbstream >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::OperatepbstreamResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::OperatepbstreamResponse> should match 
// service_traits::DataType< ::cartographer_ros_msgs::Operatepbstream > 
template<>
struct DataType< ::cartographer_ros_msgs::OperatepbstreamResponse>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::Operatepbstream >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::OperatepbstreamResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_OPERATEPBSTREAM_H
