// Generated by gencpp from file cartographer_ros_msgs/RebuildMap.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_REBUILDMAP_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_REBUILDMAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cartographer_ros_msgs
{
template <class ContainerAllocator>
struct RebuildMap_
{
  typedef RebuildMap_<ContainerAllocator> Type;

  RebuildMap_()
    : hit_prob(0.0)
    , miss_prob(0.0)
    , dis(0.0)
    , theta(0.0)  {
    }
  RebuildMap_(const ContainerAllocator& _alloc)
    : hit_prob(0.0)
    , miss_prob(0.0)
    , dis(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef float _hit_prob_type;
  _hit_prob_type hit_prob;

   typedef float _miss_prob_type;
  _miss_prob_type miss_prob;

   typedef float _dis_type;
  _dis_type dis;

   typedef float _theta_type;
  _theta_type theta;




  typedef boost::shared_ptr< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> const> ConstPtr;

}; // struct RebuildMap_

typedef ::cartographer_ros_msgs::RebuildMap_<std::allocator<void> > RebuildMap;

typedef boost::shared_ptr< ::cartographer_ros_msgs::RebuildMap > RebuildMapPtr;
typedef boost::shared_ptr< ::cartographer_ros_msgs::RebuildMap const> RebuildMapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cartographer_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'cartographer_ros_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_slam/cartographer_superbuild/cartographer_ros/cartographer_ros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34262ddb2e3ed671445a8c1fe1329a99";
  }

  static const char* value(const ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34262ddb2e3ed671ULL;
  static const uint64_t static_value2 = 0x445a8c1fe1329a99ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartographer_ros_msgs/RebuildMap";
  }

  static const char* value(const ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 hit_prob\n\
float32 miss_prob\n\
float32 dis\n\
float32 theta\n\
\n\
";
  }

  static const char* value(const ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hit_prob);
      stream.next(m.miss_prob);
      stream.next(m.dis);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RebuildMap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartographer_ros_msgs::RebuildMap_<ContainerAllocator>& v)
  {
    s << indent << "hit_prob: ";
    Printer<float>::stream(s, indent + "  ", v.hit_prob);
    s << indent << "miss_prob: ";
    Printer<float>::stream(s, indent + "  ", v.miss_prob);
    s << indent << "dis: ";
    Printer<float>::stream(s, indent + "  ", v.dis);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_REBUILDMAP_H
