// Generated by gencpp from file cartographer_ros_msgs/SetFilterModeRequest.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_SETFILTERMODEREQUEST_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_SETFILTERMODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cartographer_ros_msgs
{
template <class ContainerAllocator>
struct SetFilterModeRequest_
{
  typedef SetFilterModeRequest_<ContainerAllocator> Type;

  SetFilterModeRequest_()
    : open_filter(false)  {
    }
  SetFilterModeRequest_(const ContainerAllocator& _alloc)
    : open_filter(false)  {
  (void)_alloc;
    }



   typedef uint8_t _open_filter_type;
  _open_filter_type open_filter;




  typedef boost::shared_ptr< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFilterModeRequest_

typedef ::cartographer_ros_msgs::SetFilterModeRequest_<std::allocator<void> > SetFilterModeRequest;

typedef boost::shared_ptr< ::cartographer_ros_msgs::SetFilterModeRequest > SetFilterModeRequestPtr;
typedef boost::shared_ptr< ::cartographer_ros_msgs::SetFilterModeRequest const> SetFilterModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cartographer_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'cartographer_ros_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_slam/cartographer_superbuild/cartographer_ros/cartographer_ros_msgs/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "427233f9a6763f6ca0d5e3da5ec4c223";
  }

  static const char* value(const ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x427233f9a6763f6cULL;
  static const uint64_t static_value2 = 0xa0d5e3da5ec4c223ULL;
};

template<class ContainerAllocator>
struct DataType< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cartographer_ros_msgs/SetFilterModeRequest";
  }

  static const char* value(const ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool open_filter\n\
";
  }

  static const char* value(const ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.open_filter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFilterModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cartographer_ros_msgs::SetFilterModeRequest_<ContainerAllocator>& v)
  {
    s << indent << "open_filter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.open_filter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_SETFILTERMODEREQUEST_H
