// Generated by gencpp from file cartographer_ros_msgs/SetFilterMode.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_SETFILTERMODE_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_SETFILTERMODE_H

#include <ros/service_traits.h>


#include <cartographer_ros_msgs/SetFilterModeRequest.h>
#include <cartographer_ros_msgs/SetFilterModeResponse.h>


namespace cartographer_ros_msgs
{

struct SetFilterMode
{

typedef SetFilterModeRequest Request;
typedef SetFilterModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetFilterMode
} // namespace cartographer_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cartographer_ros_msgs::SetFilterMode > {
  static const char* value()
  {
    return "d4bf3ba13370f4cc90a0b1718b13ecd4";
  }

  static const char* value(const ::cartographer_ros_msgs::SetFilterMode&) { return value(); }
};

template<>
struct DataType< ::cartographer_ros_msgs::SetFilterMode > {
  static const char* value()
  {
    return "cartographer_ros_msgs/SetFilterMode";
  }

  static const char* value(const ::cartographer_ros_msgs::SetFilterMode&) { return value(); }
};


// service_traits::MD5Sum< ::cartographer_ros_msgs::SetFilterModeRequest> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::SetFilterMode > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::SetFilterModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::SetFilterMode >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::SetFilterModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::SetFilterModeRequest> should match 
// service_traits::DataType< ::cartographer_ros_msgs::SetFilterMode > 
template<>
struct DataType< ::cartographer_ros_msgs::SetFilterModeRequest>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::SetFilterMode >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::SetFilterModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cartographer_ros_msgs::SetFilterModeResponse> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::SetFilterMode > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::SetFilterModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::SetFilterMode >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::SetFilterModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::SetFilterModeResponse> should match 
// service_traits::DataType< ::cartographer_ros_msgs::SetFilterMode > 
template<>
struct DataType< ::cartographer_ros_msgs::SetFilterModeResponse>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::SetFilterMode >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::SetFilterModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_SETFILTERMODE_H
