// Generated by gencpp from file cartographer_ros_msgs/StatusSwitch.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_STATUSSWITCH_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_STATUSSWITCH_H

#include <ros/service_traits.h>


#include <cartographer_ros_msgs/StatusSwitchRequest.h>
#include <cartographer_ros_msgs/StatusSwitchResponse.h>


namespace cartographer_ros_msgs
{

struct StatusSwitch
{

typedef StatusSwitchRequest Request;
typedef StatusSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StatusSwitch
} // namespace cartographer_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cartographer_ros_msgs::StatusSwitch > {
  static const char* value()
  {
    return "e91527c3b01a6f0efe28aadb6967cb6d";
  }

  static const char* value(const ::cartographer_ros_msgs::StatusSwitch&) { return value(); }
};

template<>
struct DataType< ::cartographer_ros_msgs::StatusSwitch > {
  static const char* value()
  {
    return "cartographer_ros_msgs/StatusSwitch";
  }

  static const char* value(const ::cartographer_ros_msgs::StatusSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::cartographer_ros_msgs::StatusSwitchRequest> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::StatusSwitch > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::StatusSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::StatusSwitch >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::StatusSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::StatusSwitchRequest> should match 
// service_traits::DataType< ::cartographer_ros_msgs::StatusSwitch > 
template<>
struct DataType< ::cartographer_ros_msgs::StatusSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::StatusSwitch >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::StatusSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cartographer_ros_msgs::StatusSwitchResponse> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::StatusSwitch > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::StatusSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::StatusSwitch >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::StatusSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::StatusSwitchResponse> should match 
// service_traits::DataType< ::cartographer_ros_msgs::StatusSwitch > 
template<>
struct DataType< ::cartographer_ros_msgs::StatusSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::StatusSwitch >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::StatusSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_STATUSSWITCH_H
