// Generated by gencpp from file cartographer_ros_msgs/WriteVslamPose.msg
// DO NOT EDIT!


#ifndef CARTOGRAPHER_ROS_MSGS_MESSAGE_WRITEVSLAMPOSE_H
#define CARTOGRAPHER_ROS_MSGS_MESSAGE_WRITEVSLAMPOSE_H

#include <ros/service_traits.h>


#include <cartographer_ros_msgs/WriteVslamPoseRequest.h>
#include <cartographer_ros_msgs/WriteVslamPoseResponse.h>


namespace cartographer_ros_msgs
{

struct WriteVslamPose
{

typedef WriteVslamPoseRequest Request;
typedef WriteVslamPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteVslamPose
} // namespace cartographer_ros_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cartographer_ros_msgs::WriteVslamPose > {
  static const char* value()
  {
    return "c4b744c4e970327c482e45a815076dee";
  }

  static const char* value(const ::cartographer_ros_msgs::WriteVslamPose&) { return value(); }
};

template<>
struct DataType< ::cartographer_ros_msgs::WriteVslamPose > {
  static const char* value()
  {
    return "cartographer_ros_msgs/WriteVslamPose";
  }

  static const char* value(const ::cartographer_ros_msgs::WriteVslamPose&) { return value(); }
};


// service_traits::MD5Sum< ::cartographer_ros_msgs::WriteVslamPoseRequest> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::WriteVslamPose > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::WriteVslamPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::WriteVslamPose >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::WriteVslamPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::WriteVslamPoseRequest> should match 
// service_traits::DataType< ::cartographer_ros_msgs::WriteVslamPose > 
template<>
struct DataType< ::cartographer_ros_msgs::WriteVslamPoseRequest>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::WriteVslamPose >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::WriteVslamPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cartographer_ros_msgs::WriteVslamPoseResponse> should match 
// service_traits::MD5Sum< ::cartographer_ros_msgs::WriteVslamPose > 
template<>
struct MD5Sum< ::cartographer_ros_msgs::WriteVslamPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cartographer_ros_msgs::WriteVslamPose >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::WriteVslamPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cartographer_ros_msgs::WriteVslamPoseResponse> should match 
// service_traits::DataType< ::cartographer_ros_msgs::WriteVslamPose > 
template<>
struct DataType< ::cartographer_ros_msgs::WriteVslamPoseResponse>
{
  static const char* value()
  {
    return DataType< ::cartographer_ros_msgs::WriteVslamPose >::value();
  }
  static const char* value(const ::cartographer_ros_msgs::WriteVslamPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CARTOGRAPHER_ROS_MSGS_MESSAGE_WRITEVSLAMPOSE_H
