// Generated by gencpp from file keenon_vslam_msgs/VSLAMMapping.msg
// DO NOT EDIT!


#ifndef KEENON_VSLAM_MSGS_MESSAGE_VSLAMMAPPING_H
#define KEENON_VSLAM_MSGS_MESSAGE_VSLAMMAPPING_H

#include <ros/service_traits.h>


#include <keenon_vslam_msgs/VSLAMMappingRequest.h>
#include <keenon_vslam_msgs/VSLAMMappingResponse.h>


namespace keenon_vslam_msgs
{

struct VSLAMMapping
{

typedef VSLAMMappingRequest Request;
typedef VSLAMMappingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VSLAMMapping
} // namespace keenon_vslam_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::keenon_vslam_msgs::VSLAMMapping > {
  static const char* value()
  {
    return "1bd103c1c478d6c9ac445349ec564625";
  }

  static const char* value(const ::keenon_vslam_msgs::VSLAMMapping&) { return value(); }
};

template<>
struct DataType< ::keenon_vslam_msgs::VSLAMMapping > {
  static const char* value()
  {
    return "keenon_vslam_msgs/VSLAMMapping";
  }

  static const char* value(const ::keenon_vslam_msgs::VSLAMMapping&) { return value(); }
};


// service_traits::MD5Sum< ::keenon_vslam_msgs::VSLAMMappingRequest> should match 
// service_traits::MD5Sum< ::keenon_vslam_msgs::VSLAMMapping > 
template<>
struct MD5Sum< ::keenon_vslam_msgs::VSLAMMappingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::keenon_vslam_msgs::VSLAMMapping >::value();
  }
  static const char* value(const ::keenon_vslam_msgs::VSLAMMappingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::keenon_vslam_msgs::VSLAMMappingRequest> should match 
// service_traits::DataType< ::keenon_vslam_msgs::VSLAMMapping > 
template<>
struct DataType< ::keenon_vslam_msgs::VSLAMMappingRequest>
{
  static const char* value()
  {
    return DataType< ::keenon_vslam_msgs::VSLAMMapping >::value();
  }
  static const char* value(const ::keenon_vslam_msgs::VSLAMMappingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::keenon_vslam_msgs::VSLAMMappingResponse> should match 
// service_traits::MD5Sum< ::keenon_vslam_msgs::VSLAMMapping > 
template<>
struct MD5Sum< ::keenon_vslam_msgs::VSLAMMappingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::keenon_vslam_msgs::VSLAMMapping >::value();
  }
  static const char* value(const ::keenon_vslam_msgs::VSLAMMappingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::keenon_vslam_msgs::VSLAMMappingResponse> should match 
// service_traits::DataType< ::keenon_vslam_msgs::VSLAMMapping > 
template<>
struct DataType< ::keenon_vslam_msgs::VSLAMMappingResponse>
{
  static const char* value()
  {
    return DataType< ::keenon_vslam_msgs::VSLAMMapping >::value();
  }
  static const char* value(const ::keenon_vslam_msgs::VSLAMMappingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KEENON_VSLAM_MSGS_MESSAGE_VSLAMMAPPING_H
