// Generated by gencpp from file keenon_vslam_msgs/VSLAMMappingRequest.msg
// DO NOT EDIT!


#ifndef KEENON_VSLAM_MSGS_MESSAGE_VSLAMMAPPINGREQUEST_H
#define KEENON_VSLAM_MSGS_MESSAGE_VSLAMMAPPINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace keenon_vslam_msgs
{
template <class ContainerAllocator>
struct VSLAMMappingRequest_
{
  typedef VSLAMMappingRequest_<ContainerAllocator> Type;

  VSLAMMappingRequest_()
    : option(0)  {
    }
  VSLAMMappingRequest_(const ContainerAllocator& _alloc)
    : option(0)  {
  (void)_alloc;
    }



   typedef int16_t _option_type;
  _option_type option;




  typedef boost::shared_ptr< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VSLAMMappingRequest_

typedef ::keenon_vslam_msgs::VSLAMMappingRequest_<std::allocator<void> > VSLAMMappingRequest;

typedef boost::shared_ptr< ::keenon_vslam_msgs::VSLAMMappingRequest > VSLAMMappingRequestPtr;
typedef boost::shared_ptr< ::keenon_vslam_msgs::VSLAMMappingRequest const> VSLAMMappingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace keenon_vslam_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'keenon_vslam_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_common/keenon_msgs/keenon_vslam_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe71a5911ada5d7e49223ae9d8654f9a";
  }

  static const char* value(const ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe71a5911ada5d7eULL;
  static const uint64_t static_value2 = 0x49223ae9d8654f9aULL;
};

template<class ContainerAllocator>
struct DataType< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "keenon_vslam_msgs/VSLAMMappingRequest";
  }

  static const char* value(const ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
int16 option\n\
";
  }

  static const char* value(const ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.option);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VSLAMMappingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::keenon_vslam_msgs::VSLAMMappingRequest_<ContainerAllocator>& v)
  {
    s << indent << "option: ";
    Printer<int16_t>::stream(s, indent + "  ", v.option);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KEENON_VSLAM_MSGS_MESSAGE_VSLAMMAPPINGREQUEST_H
