// Generated by gencpp from file keenon_vslam_msgs/VSLAMMappingResponse.msg
// DO NOT EDIT!


#ifndef KEENON_VSLAM_MSGS_MESSAGE_VSLAMMAPPINGRESPONSE_H
#define KEENON_VSLAM_MSGS_MESSAGE_VSLAMMAPPINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace keenon_vslam_msgs
{
template <class ContainerAllocator>
struct VSLAMMappingResponse_
{
  typedef VSLAMMappingResponse_<ContainerAllocator> Type;

  VSLAMMappingResponse_()
    : stamp()
    , floor(0)
    , db_key_sn()
    , db_key_time()
    , db_key_sub_db_desc()
    , option_result(false)  {
    }
  VSLAMMappingResponse_(const ContainerAllocator& _alloc)
    : stamp()
    , floor(0)
    , db_key_sn(_alloc)
    , db_key_time(_alloc)
    , db_key_sub_db_desc(_alloc)
    , option_result(false)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int16_t _floor_type;
  _floor_type floor;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _db_key_sn_type;
  _db_key_sn_type db_key_sn;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _db_key_time_type;
  _db_key_time_type db_key_time;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _db_key_sub_db_desc_type;
  _db_key_sub_db_desc_type db_key_sub_db_desc;

   typedef uint8_t _option_result_type;
  _option_result_type option_result;




  typedef boost::shared_ptr< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VSLAMMappingResponse_

typedef ::keenon_vslam_msgs::VSLAMMappingResponse_<std::allocator<void> > VSLAMMappingResponse;

typedef boost::shared_ptr< ::keenon_vslam_msgs::VSLAMMappingResponse > VSLAMMappingResponsePtr;
typedef boost::shared_ptr< ::keenon_vslam_msgs::VSLAMMappingResponse const> VSLAMMappingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace keenon_vslam_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'keenon_vslam_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_common/keenon_msgs/keenon_vslam_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90f865a5a9beda019c8a581b1ca10bab";
  }

  static const char* value(const ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90f865a5a9beda01ULL;
  static const uint64_t static_value2 = 0x9c8a581b1ca10babULL;
};

template<class ContainerAllocator>
struct DataType< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "keenon_vslam_msgs/VSLAMMappingResponse";
  }

  static const char* value(const ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
time stamp\n\
int16 floor\n\
string db_key_sn\n\
string db_key_time\n\
string db_key_sub_db_desc\n\
bool option_result\n\
";
  }

  static const char* value(const ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.floor);
      stream.next(m.db_key_sn);
      stream.next(m.db_key_time);
      stream.next(m.db_key_sub_db_desc);
      stream.next(m.option_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VSLAMMappingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::keenon_vslam_msgs::VSLAMMappingResponse_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "floor: ";
    Printer<int16_t>::stream(s, indent + "  ", v.floor);
    s << indent << "db_key_sn: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.db_key_sn);
    s << indent << "db_key_time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.db_key_time);
    s << indent << "db_key_sub_db_desc: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.db_key_sub_db_desc);
    s << indent << "option_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.option_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KEENON_VSLAM_MSGS_MESSAGE_VSLAMMAPPINGRESPONSE_H
