// Generated by gencpp from file keenon_label_msgs/gmapping_label_array.msg
// DO NOT EDIT!


#ifndef KEENON_LABEL_MSGS_MESSAGE_GMAPPING_LABEL_ARRAY_H
#define KEENON_LABEL_MSGS_MESSAGE_GMAPPING_LABEL_ARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <keenon_label_msgs/gmapping_label.h>

namespace keenon_label_msgs
{
template <class ContainerAllocator>
struct gmapping_label_array_
{
  typedef gmapping_label_array_<ContainerAllocator> Type;

  gmapping_label_array_()
    : label()
    , show(false)  {
    }
  gmapping_label_array_(const ContainerAllocator& _alloc)
    : label(_alloc)
    , show(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >::other >  _label_type;
  _label_type label;

   typedef uint8_t _show_type;
  _show_type show;




  typedef boost::shared_ptr< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> const> ConstPtr;

}; // struct gmapping_label_array_

typedef ::keenon_label_msgs::gmapping_label_array_<std::allocator<void> > gmapping_label_array;

typedef boost::shared_ptr< ::keenon_label_msgs::gmapping_label_array > gmapping_label_arrayPtr;
typedef boost::shared_ptr< ::keenon_label_msgs::gmapping_label_array const> gmapping_label_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace keenon_label_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'keenon_label_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_common/keenon_msgs/keenon_label_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5fbe04a6b16bde66803610d7bbf55d6";
  }

  static const char* value(const ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5fbe04a6b16bde6ULL;
  static const uint64_t static_value2 = 0x6803610d7bbf55d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "keenon_label_msgs/gmapping_label_array";
  }

  static const char* value(const ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "keenon_label_msgs/gmapping_label[] label\n\
bool show\n\
================================================================================\n\
MSG: keenon_label_msgs/gmapping_label\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 yaw\n\
float64 roll\n\
float64 pitch\n\
int64 id\n\
int64 floor_id\n\
";
  }

  static const char* value(const ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.show);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gmapping_label_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::keenon_label_msgs::gmapping_label_array_<ContainerAllocator>& v)
  {
    s << indent << "label[]" << std::endl;
    for (size_t i = 0; i < v.label.size(); ++i)
    {
      s << indent << "  label[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >::stream(s, indent + "    ", v.label[i]);
    }
    s << indent << "show: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.show);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KEENON_LABEL_MSGS_MESSAGE_GMAPPING_LABEL_ARRAY_H
