// Generated by gencpp from file keenon_label_msgs/gmapping_label.msg
// DO NOT EDIT!


#ifndef KEENON_LABEL_MSGS_MESSAGE_GMAPPING_LABEL_H
#define KEENON_LABEL_MSGS_MESSAGE_GMAPPING_LABEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace keenon_label_msgs
{
template <class ContainerAllocator>
struct gmapping_label_
{
  typedef gmapping_label_<ContainerAllocator> Type;

  gmapping_label_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , roll(0.0)
    , pitch(0.0)
    , id(0)
    , floor_id(0)  {
    }
  gmapping_label_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , yaw(0.0)
    , roll(0.0)
    , pitch(0.0)
    , id(0)
    , floor_id(0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef int64_t _id_type;
  _id_type id;

   typedef int64_t _floor_id_type;
  _floor_id_type floor_id;




  typedef boost::shared_ptr< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> const> ConstPtr;

}; // struct gmapping_label_

typedef ::keenon_label_msgs::gmapping_label_<std::allocator<void> > gmapping_label;

typedef boost::shared_ptr< ::keenon_label_msgs::gmapping_label > gmapping_labelPtr;
typedef boost::shared_ptr< ::keenon_label_msgs::gmapping_label const> gmapping_labelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::keenon_label_msgs::gmapping_label_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace keenon_label_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'keenon_label_msgs': ['/workdir/catkin_ws/src/keenon_ros/keenon_common/keenon_msgs/keenon_label_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6367d082b474d73c387980bd354d8e4f";
  }

  static const char* value(const ::keenon_label_msgs::gmapping_label_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6367d082b474d73cULL;
  static const uint64_t static_value2 = 0x387980bd354d8e4fULL;
};

template<class ContainerAllocator>
struct DataType< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >
{
  static const char* value()
  {
    return "keenon_label_msgs/gmapping_label";
  }

  static const char* value(const ::keenon_label_msgs::gmapping_label_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
float64 yaw\n\
float64 roll\n\
float64 pitch\n\
int64 id\n\
int64 floor_id\n\
";
  }

  static const char* value(const ::keenon_label_msgs::gmapping_label_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.yaw);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.id);
      stream.next(m.floor_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gmapping_label_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::keenon_label_msgs::gmapping_label_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::keenon_label_msgs::gmapping_label_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "floor_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.floor_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KEENON_LABEL_MSGS_MESSAGE_GMAPPING_LABEL_H
