# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from keenon_label_msgs/gmapping_label_array.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import keenon_label_msgs.msg

class gmapping_label_array(genpy.Message):
  _md5sum = "b5fbe04a6b16bde66803610d7bbf55d6"
  _type = "keenon_label_msgs/gmapping_label_array"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """keenon_label_msgs/gmapping_label[] label
bool show
================================================================================
MSG: keenon_label_msgs/gmapping_label
float64 x
float64 y
float64 z
float64 yaw
float64 roll
float64 pitch
int64 id
int64 floor_id
"""
  __slots__ = ['label','show']
  _slot_types = ['keenon_label_msgs/gmapping_label[]','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       label,show

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gmapping_label_array, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.label is None:
        self.label = []
      if self.show is None:
        self.show = False
    else:
      self.label = []
      self.show = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.label)
      buff.write(_struct_I.pack(length))
      for val1 in self.label:
        _x = val1
        buff.write(_struct_6d2q.pack(_x.x, _x.y, _x.z, _x.yaw, _x.roll, _x.pitch, _x.id, _x.floor_id))
      buff.write(_struct_B.pack(self.show))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.label is None:
        self.label = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.label = []
      for i in range(0, length):
        val1 = keenon_label_msgs.msg.gmapping_label()
        _x = val1
        start = end
        end += 64
        (_x.x, _x.y, _x.z, _x.yaw, _x.roll, _x.pitch, _x.id, _x.floor_id,) = _struct_6d2q.unpack(str[start:end])
        self.label.append(val1)
      start = end
      end += 1
      (self.show,) = _struct_B.unpack(str[start:end])
      self.show = bool(self.show)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.label)
      buff.write(_struct_I.pack(length))
      for val1 in self.label:
        _x = val1
        buff.write(_struct_6d2q.pack(_x.x, _x.y, _x.z, _x.yaw, _x.roll, _x.pitch, _x.id, _x.floor_id))
      buff.write(_struct_B.pack(self.show))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.label is None:
        self.label = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.label = []
      for i in range(0, length):
        val1 = keenon_label_msgs.msg.gmapping_label()
        _x = val1
        start = end
        end += 64
        (_x.x, _x.y, _x.z, _x.yaw, _x.roll, _x.pitch, _x.id, _x.floor_id,) = _struct_6d2q.unpack(str[start:end])
        self.label.append(val1)
      start = end
      end += 1
      (self.show,) = _struct_B.unpack(str[start:end])
      self.show = bool(self.show)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
_struct_6d2q = struct.Struct("<6d2q")
